BEGIN TRY

BEGIN TRAN;

-- AddForeignKey
ALTER TABLE [dbo].[tblCart] ADD CONSTRAINT [FK_Cart_WaiterMaster] FOREIGN KEY ([WaiterName]) REFERENCES [dbo].[WaiterMaster]([WaiterName]) ON DELETE NO ACTION ON UPDATE CASCADE;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
